<?php

class {ClassName} extends KpdMigration
{
//                                      ALIAS             //ct mn tg lg rc sc sr ix tm md st sm  ICON              Ед.число                   SEF               ед.ч. род.падеж          Мн.число                  Меню в админке
//Object::idIndex         =>array(100,':site'        ,''   , 0, 0, 0, 0, 1, 0, 0, 0, 0,  0, 0,-1, ''                , 'Главная'                , 'site'           ,''                      ,'Главная'               , 'Главная'               ),
    public $fileUpdate = array(
        'models/Object.php'=>array(
            'OBJECT-LIST'=>array(
/*KPDMFU-START-MIGRATE-OBJECT*/
                Object::idIndex        =>array( // 'oid' => 100,
                    'chars'=>array(':index', '', '', 'site'),
                    'label'=>array('Главная', 'Главная', 'Главная', ''),
                    'have' => array('module','reclame','sitemap'=>-1),
                ),
                Object::idNews         =>array( // 'oid' => 1,
                    'chars'=>array('news', 'n', 'news', 'novosti'),
                    'label'=>array('Новости', 'Новость', 'Новости', 'новости'),
                    'have' => array('module','category'=>2,'mention','tag','reclame'=>2,'social','search'=>-4,'theme','stat'),
                ),
                Object::idBlog         =>array( // 'oid' => 2,
                    'chars'=>array('blog', 'b', 'address', 'blog/read'),
                    'label'=>array('Блоги', 'Блог', 'Блоги', 'блога'),
                    'have' => array('module','mention','tag'=>4,'reclame'=>2,'search','stripe'=>3,'theme'=>3),
                ),
                Object::idUser         =>array( // 'oid' => 3,
                    'chars'=>array('user', 'u', 'phonebook', 'user'),
                    'label'=>array('Пользователи', 'Пользователь', 'Пользователи', 'пользователя'),
                    'have' => array('module','log','category'),
                ),
                Object::idMenu         =>array( // 'oid' => 4,
                    'chars'=>array('menu', 'm', 'list', 'menu'),
                    'label'=>array('Меню', 'Меню', 'Меню', 'меню'),
                    'have' => array('module','log'),
                ),
                Object::idPage         =>array( // 'oid' => 5,
                    'chars'=>array('page', 'p', 'foldertree', 'page'),
                    'label'=>array('Редактор страниц', 'Страница', 'Страницы', 'страницы'),
                    'have' => array('module','log','reclame'=>2,'sitemap'),
                ),
                Object::idCategory     =>array( // 'oid' => 6,
                    'chars'=>array('category', 'c', 'layers', 'category'),
                    'label'=>array('Рубрики', 'Рубрика', 'Рубрики', 'рубрики'),
                    'have' => array('module'),
                ),
                Object::idSetting      =>array( // 'oid' => 7,
                    'chars'=>array('setting', 's', 'settings4', 'setting'),
                    'label'=>array('Настройки', 'Параметр', 'Параметры', 'параметра'),
                    'have' => array('module','log'),
                ),
                Object::idGallery      =>array( // 'oid' => 8,
                    'chars'=>array('gallery', 'g', 'camera', 'photo'),
                    'label'=>array('Фотогалереи', 'Фото по теме', 'Фото по теме', 'фотогалереи'),
                    'have' => array('module','mention','tag'=>7,'reclame'=>2,'search'=>6,'theme'=>3),
                ),
                Object::idVideo        =>array( // 'oid' => 9,
                    'chars'=>array('video', 'v', 'play2', 'video/read'),
                    'label'=>array('Видеоновости', 'Видео', 'Видео', 'видео'),
                    'have' => array('module','category','mention','tag'=>12,'reclame'=>2,'theme'=>4),
                ),
                Object::idRegion       =>array( // 'oid' => 10,
                    'chars'=>array(':region', '', '', ':region'),
                    'label'=>array('', 'Регион', 'Регионы', 'региона'),
                    'have' => array('module','category'),
                ),
                Object::idBranch       =>array( // 'oid' => 11,
                    'chars'=>array(':branch', '', '', ':branch'),
                    'label'=>array('', 'Отрасль', 'Отрасли', 'отрасли'),
                    'have' => array('module','category'),
                ),
                Object::idCompany      =>array( // 'oid' => 12,
                    'chars'=>array('company', 'k', 'briefcase2', 'kompanii'),
                    'label'=>array('Компании', 'Компания', 'Компании', 'компании'),
                    'have' => array('module','mention','tag'=>6,'reclame'=>2,'search'=>-1,'theme'=>2,'stat'=>2),
                ),
                Object::idBrand        =>array( // 'oid' => 13,
                    'chars'=>array('brand', 'r', 'starfull', 'brand'),
                    'label'=>array('Бренды', 'Бренд', 'Бренды', 'бренда'),
                    'have' => array('module','mention','tag'=>5,'theme'),
                ),
                Object::idDossier      =>array( // 'oid' => 14,
                    'chars'=>array('dossier', 'd', 'businesscard2', 'dosye'),
                    'label'=>array('Досье', 'Досье', 'Досье', 'досье'),
                    'have' => array('module','mention','tag'=>2,'reclame'=>2,'social','search'=>-2,'theme'=>2,'stat'=>3),
                ),
                Object::idEvent        =>array( // 'oid' => 15,
                    'chars'=>array('event', 'ev', 'alarm', 'sobytiya'),
                    'label'=>array('События', 'Событие', 'События', 'события'),
                    'have' => array('module','category','tag'=>3,'reclame'=>2,'social','search'=>-3,'theme','stat'=>4),
                ),
                Object::idInterview    =>array( // 'oid' => 16,
                    'chars'=>array('interview', 've', 'microphone', 'interview'),
                    'label'=>array('Интервью', 'Интервью', 'Интервью', 'интервью'),
                    'have' => array('module','mention','tag'=>9,'reclame'=>2,'social','search'=>2,'stripe'=>2,'theme'=>3),
                ),
                Object::idHistory      =>array( // 'oid' => 17,
                    'chars'=>array('history', 'hs', 'trophy', 'istorii-uspeha'),
                    'label'=>array('Истории успеха', 'История успеха', 'Истории успеха', 'истории успеха'),
                    'have' => array('module','mention','tag'=>8,'reclame'=>2,'social','search'=>4,'stripe'=>4,'theme'=>3),
                ),
                Object::idInfographics =>array( // 'oid' => 18,
                    'chars'=>array('infographics', 'gr', 'infographic', 'infographics'),
                    'label'=>array('Инфографика', 'Инфографика', 'Инфографики', 'инфографики'),
                    'have' => array('module','reclame'=>2),
                ),
                Object::idRating       =>array( // 'oid' => 19,
                    'chars'=>array('rating', 'rt', 'podium', 'rating'),
                    'label'=>array('Рейтинги', 'Рейтинг', 'Рейтинги', 'рейтинга'),
                    'have' => array('module','mention','reclame'=>2,'stripe'=>5,'theme'),
                ),
                Object::idMember       =>array( // 'oid' => 20,
                    'chars'=>array('member', 'mb', '', 'member'),
                    'label'=>array('Рейтинг', 'Участник', 'Участники', 'участника'),
                    'have' => array('module','search'=>5),
                ),
                Object::idField        =>array( // 'oid' => 21,
                    'chars'=>array('field', 'fl', '', ':field'),
                    'label'=>array('', 'Доп.поле', 'Доп.поля', 'доп.поля'),
                    'have' => array('module'),
                ),
                Object::idValue        =>array( // 'oid' => 22,
                    'chars'=>array('value', 'vl', '', ':value'),
                    'label'=>array('', 'Значение', 'Значения', 'значения'),
                    'have' => array('module'),
                ),
                Object::idBanner       =>array( // 'oid' => 23,
                    'chars'=>array('banner', 'bn', 'monitor', ':banner'),
                    'label'=>array('Баннеры', 'Баннер', 'Баннеры', 'баннера'),
                    'have' => array('module','log'),
                ),
                Object::idReclame      =>array( // 'oid' => 24,
                    'chars'=>array('reclame', 'rc', 'piggybank', ':reclame'),
                    'label'=>array('Реклама', 'Реклама', 'Реклама', 'рекламы'),
                    'have' => array('module'),
                ),
                Object::idPlace        =>array( // 'oid' => 25,
                    'chars'=>array('place', 'pl', '', ':place'),
                    'label'=>array('Редактирование рекламы', 'Баннероместо', 'Баннероместа', 'баннероместа'),
                    'have' => array('module'),
                ),
                Object::idFolder       =>array( // 'oid' => 26,
                    'chars'=>array('folder', 'f', '', 'folder'),
                    'label'=>array('', 'Папка', 'Папки', 'папки'),
                    'have' => array('module'),
                ),
                Object::idShortcutBar  =>array( // 'oid' => 27,
                    'chars'=>array('shortcutBar', 'sb', '', 'shortcut-bar'),
                    'label'=>array('', 'Панель быстрого старта', 'Панели быстрого старта', 'панели быстрого старта'),
                    'have' => array('module'),
                ),
                Object::idTask         =>array( // 'oid' => 28,
                    'chars'=>array('task', 'ts', 'settings5', ':task'),
                    'label'=>array('Расписание', 'Расписание', 'Расписание', 'задачи'),
                    'have' => array('module','log'),
                ),
                Object::idProduct      =>array( // 'oid' => 29,
                    'chars'=>array('product', 'pr', '', ':product'),
                    'label'=>array('', 'Товар', 'Товары', 'товара'),
                    'have' => array('module'),
                ),
                Object::idLook         =>array( // 'oid' => 30,
                    'chars'=>array('look', 'lk', 'shoppingcart', 'look'),
                    'label'=>array('Луки', 'Лук', 'Луки', 'лука'),
                    'have' => array('module'),
                ),
                Object::idXml          =>array( // 'oid' => 31,
                    'chars'=>array(':xml', '', 'favoritefolder', ':xml'),
                    'label'=>array('Загрузка данных из XML', 'Загрузка', 'Загрузка данных из XML', 'загрузки'),
                    'have' => array('module'),
                ),
                Object::idSeason       =>array( // 'oid' => 32,
                    'chars'=>array(':season', '', '', ':season'),
                    'label'=>array('', 'Сезон', 'Сезоны', 'сезона'),
                    'have' => array('module'),
                ),
                Object::idStyle        =>array( // 'oid' => 33,
                    'chars'=>array(':style', '', '', ':style'),
                    'label'=>array('', 'Стиль', 'Стили', 'стиля'),
                    'have' => array('module'),
                ),
                Object::idAttribute    =>array( // 'oid' => 34,
                    'chars'=>array('attribute', 'at', 'wallet', ':attribute'),
                    'label'=>array('Атрибуты', 'Атрибут', 'Атрибуты', 'атрибуты'),
                    'have' => array('module'),
                ),
                Object::idLookitem     =>array( // 'oid' => 35,
                    'chars'=>array('lookitem', 'it', '', ':lookitem'),
                    'label'=>array('', 'Фрейм', 'Фреймы', 'фрейма'),
                    'have' => array('module'),
                ),
                Object::idTag          =>array( // 'oid' => 36,
                    'chars'=>array('tag', 't', 'wallet', ':tag'),
                    'label'=>array('Теги', 'Тег', 'Теги', 'тега'),
                    'have' => array('module'),
                ),
                Object::idFile         =>array( // 'oid' => 37,
                    'chars'=>array('file', '', 'filemanager', ':file'),
                    'label'=>array('Управление файлами', 'Файл', 'Файлы', 'файла'),
                    'have' => array('module','log'),
                ),
                Object::idLog          =>array( // 'oid' => 38,
                    'chars'=>array('log', 'z', 'darthvader', ':log'),
                    'label'=>array('Протокол изменений', 'Протокол', 'Изменения', 'изменения'),
                    'have' => array('module'),
                ),
                Object::idHead         =>array( // 'oid' => 39,
                    'chars'=>array('head', 'h', 'layers', ':head'),
                    'label'=>array('Разделы', 'Раздел', 'Разделы', 'раздела'),
                    'have' => array('module'),
                ),
                Object::idClientlogo   =>array( // 'oid' => 40,
                    'chars'=>array('clientlogo', 'cll', 'starempty', ':сlientlogo'),
                    'label'=>array('Логотипы клиентов', 'Логотипы клиентов', 'Логотипы клиентов', 'Логотипы клиентов'),
                    'have' => array('module','log','sitemap'),
                ),
                Object::idReviews      =>array( // 'oid' => 41,
                    'chars'=>array('reviews', 'rv', 'socialnetworking', ':reviews'),
                    'label'=>array('Отзывы', 'Отзывы', 'Отзывы', 'Отзывы'),
                    'have' => array('module','log'),
                ),
                Object::idStat         =>array( // 'oid' => 42,
                    'chars'=>array('stat', '', 'barchart', ':stat'),
                    'label'=>array('Статистика', 'Статистика', 'Статистику', 'статистики'),
                    'have' => array('module'),
                ),
                Object::idSpecproject  =>array( // 'oid' => 43,
                    'chars'=>array('specproject', 'sp', 'tv', 'spetsproekt'),
                    'label'=>array('Спецпроекты', 'Спецпроект', 'Спецпроект', 'спецпроекта'),
                    'have' => array('module','mention','tag'=>11,'reclame'=>2,'search'=>3,'stripe','theme'=>3),
                ),
                Object::idLifestyle    =>array( // 'oid' => 44,
                    'chars'=>array('lifestyle', 'ls', 'brush', 'lifestyle'),
                    'label'=>array('Стили жизни', 'Стиль жизни', 'Стиль жизни', 'стиля жизни'),
                    'have' => array('module','mention','tag'=>10,'reclame'=>2,'stripe'=>6,'theme'),
                ),
                Object::idProfile      =>array( // 'oid' => 45,
                    'chars'=>array('profile', 'pf', '', 'my'),
                    'label'=>array('Профили', 'Профиль', 'Профили', 'профиля'),
                    'have' => array('module'),
                ),
                Object::idReceiver     =>array( // 'oid' => 46,
                    'chars'=>array('receiver', 'rv', 'visitor', ':receiver'),
                    'label'=>array('Подписчики', 'Подписчик', 'Подписчики', 'подписчика'),
                    'have' => array('module'),
                ),
                Object::idTop100event  =>array( // 'oid' => 47,
                    'chars'=>array('top100event', 'te', '', ':top100event'),
                    'label'=>array('', 'Событие', 'События', 'события'),
                    'have' => array('module'),
                ),
                Object::idTop100member =>array( // 'oid' => 48,
                    'chars'=>array('top100member', 'tp', '', ':top100member'),
                    'label'=>array('', 'Участник', 'Участники', 'участника'),
                    'have' => array('module'),
                ),
                Object::idTop100value  =>array( // 'oid' => 49,
                    'chars'=>array('top100value', 'tv', '', ':top100value'),
                    'label'=>array('', 'Дополнительное поле', 'Доп.поля', 'доп.поля'),
                    'have' => array('module'),
                ),
                Object::idMiniGallery  =>array( // 'oid' => 50,
                    'chars'=>array('miniGallery', 'mg', 'images', 'minigallery'),
                    'label'=>array('Мини галереи', 'Мини галерея', 'Мини галереи', 'мини галереи'),
                    'have' => array('module','log'),
                ),
                Object::idSlider       =>array( // 'oid' => 51,
                    'chars'=>array('slider', 'sl', 'images', 'slider'),
                    'label'=>array('Слайды', 'Слайд', 'Слайды', 'слайда'),
                    'have' => array('module'),
                ),
                Object::idArticles     =>array( // 'oid' => 52,
                    'chars'=>array('articles', 'ar', 'address', 'articles'),
                    'label'=>array('Статьи', 'Статья', 'Статьи', 'статьи'),
                    'have' => array('module','category','tag','reclame'=>2,'stripe'=>2),
                ),
                Object::idCloud        =>array( // 'oid' => 53,
                    'chars'=>array('cloud', 'cl', 'socialnetworking', 'cloud'),
                    'label'=>array('Облако тэгов', 'Облако тэгов', 'Облако тэгов', 'облака тэков'),
                    'have' => array('module'),
                ),
                Object::idHumor        =>array( // 'oid' => 54,
                    'chars'=>array('humor', 'hm', 'island', 'humor'),
                    'label'=>array('Юмор', 'Юмор', 'Юмор', 'шутки'),
                    'have' => array('module','reclame'=>2),
                ),
                Object::idTheme        =>array( // 'oid' => 55,
                    'chars'=>array('theme', 'tm', 'superman', 'spetstemy'),
                    'label'=>array('Спецтемы', 'Спецтема', 'Спецтемы', 'спецтемы'),
                    'have' => array('module','reclame'=>2),
                ),
                Object::idDebate       =>array( // 'oid' => 56,
                    'chars'=>array('debate', 'de', 'socialnetworking', 'agrodebaty'),
                    'label'=>array('Агродебаты', 'Агродебаты', 'Агродебаты', 'агродебаты'),
                    'have' => array('module'),
                ),
                Object::idComment      =>array( // 'oid' => 57,
                    'chars'=>array('comment', 'cm', '', ':comment'),
                    'label'=>array('Комментарии', 'Комментарий', 'Комментарии', 'комментарии'),
                    'have' => array('module'),
                ),
                Object::idVote         =>array( // 'oid' => 58,
                    'chars'=>array('vote', 'tv', '', ':vote'),
                    'label'=>array('Голосование', 'Голосование', 'Голосование', 'голосование'),
                    'have' => array('module'),
                ),
                Object::idSash         =>array( // 'oid' => 59,
                    'chars'=>array('sash', 'sh', 'notes', ':sash'),
                    'label'=>array('Ленты баннеров', 'Лента баннеров', 'Баннеры', 'баннетра'),
                    'have' => array('module'),
                ),
                Object::idDynamicMenu  =>array( // 'oid' => 60,
                    'chars'=>array('dynamicMenu', '', '', ''),
                    'label'=>array('', '', 'III уровень', ''),
                    'have' => array('module'),
                ),
                Object::idKind         =>array( // 'oid' => 61,
                    'chars'=>array('kind', 'kn', 'favoritefile', ':kind'),
                    'label'=>array('Виды товаров', 'Вид товара', 'Виды товара', 'вида'),
                    'have' => array('module'),
                ),
                Object::idHead         =>array( // 'oid' => 62,
                    'chars'=>array('head', 'us', 'favoritefolder', ':uses'),
                    'label'=>array('Применение клеев', 'Применение товара', 'Применение товара', 'применения'),
                    'have' => array('module'),
                ),
                Object::idMatter       =>array( // 'oid' => 63,
                    'chars'=>array('matter', 'mt', 'appointment', ':matter'),
                    'label'=>array('Клиентские материалы', 'Клиентский материал', 'Клиенты', 'клиента'),
                    'have' => array('module','log'),
                ),
                Object::idAdvert       =>array( // 'oid' => 64,
                    'chars'=>array('advert', 'ad', 'starempty', 'ad'),
                    'label'=>array('Объявления', 'Объявления', 'Объявления', 'объявления'),
                    'have' => array('module'),
                ),
                Object::idOrganization =>array( // 'oid' => 65,
                    'chars'=>array('organization', 'or', 'briefcase2', ':org'),
                    'label'=>array('Организации', 'Организация', 'Организации', 'организации'),
                    'have' => array('module','log'),
                ),
                Object::idOpinion      =>array( // 'oid' => 66,
                    'chars'=>array('opinion', 'pn', 'rocket', ':opinion'),
                    'label'=>array('Опросы', 'Опрос', 'Опросы', 'опроса'),
                    'have' => array('module','log'),
                ),
                Object::idAnswer       =>array( // 'oid' => 67,
                    'chars'=>array('answer', 'aw', '', ':answer'),
                    'label'=>array('', 'Ответ', 'Ответы', 'ответа'),
                    'have' => array('module','log'),
                ),
                Object::idDigit        =>array( // 'oid' => 68,
                    'chars'=>array('digit', 'dg', 'calendar', 'cyfradnya'),
                    'label'=>array('Цифра дня', 'Цифра дня', 'Цифры дня', 'цифры дня'),
                    'have' => array('module','log','mention'),
                ),
                Object::idOrders       =>array( // 'oid' => 69,
                    'chars'=>array('orders', 'or', 'shoppingcart', ':order'),
                    'label'=>array('Заявки', 'Заявка', 'Заявки', 'заявки'),
                    'have' => array('module'),
                ),
                Object::idGroup        =>array( // 'oid' => 70,
                    'chars'=>array('group', 'gr', 'favoritefolder', ':group'),
                    'label'=>array('Группы пользователей', 'Группа', 'Группы', 'группы'),
                    'have' => array('module'),
                ),
                Object::idPaper        =>array( // 'oid' => 71,
                    'chars'=>array('paper', 'pp', 'mailinglists', ':paper'),
                    'label'=>array('Ценные бумаги', 'Ценная бумага', 'Ценные бумаги', 'ценной бумаги'),
                    'have' => array('module','log'),
                ),
                Object::idFaq          =>array( // 'oid' => 72,
                    'chars'=>array('faq', 'fq', 'at', 'faq'),
                    'label'=>array('Вопросы - Ответы', 'Вопрос-Ответ', 'Вопросы-Ответы', 'вопроса-ответа'),
                    'have' => array('module','category'),
                ),
                Object::idDocs         =>array( // 'oid' => 73,
                    'chars'=>array('docs', 'dc', 'favoritefile', 'docs'),
                    'label'=>array('Документация', 'Документация', 'Документация', 'документации'),
                    'have' => array('module','category','search'),
                ),
                Object::idAgency       =>array( // 'oid' => 74,
                    'chars'=>array('agency', 'ag', 'bank', 'agency'),
                    'label'=>array('Представительства', 'Представительство', 'Представительства', 'представительства'),
                    'have' => array('module','log','search'),
                ),
                Object::idClient       =>array( // 'oid' => 75,
                    'chars'=>array('client', 'cl', 'briefcase2', 'client'),
                    'label'=>array('Клиенты и объекты', 'Клиент или объект', 'Клиенты и объекты', 'клиентов и объектов'),
                    'have' => array('module','log','search'),
                ),
                Object::idQuality      =>array( // 'oid' => 76,
                    'chars'=>array('quality', 'ql', 'favoritefolder', 'quality'),
                    'label'=>array('Качество', 'Качество', 'Качество', 'документа'),
                    'have' => array('module','log','category','search'),
                ),
                Object::idSite         =>array( // 'oid' => 77,
                    'chars'=>array('site', 'si', 'stocks', ':site'),
                    'label'=>array('Сайты', 'Сайт', 'Сайты', 'сайта'),
                    'have' => array('module','log'),
                ),
                Object::idPlugin       =>array( // 'oid' => 78,
                    'chars'=>array('plugin', 'pg', 'rocket', ':plugin'),
                    'label'=>array('Плагины', 'Плагин', 'Плагины', 'плагина'),
                    'have' => array('module','log'),
                ),
                Object::idCustomer     =>array( // 'oid' => 79,
                    'chars'=>array('customer', 'ct', 'at', ':customer'),
                    'label'=>array('Клиенты', 'Клиент', 'Клиенты', 'клиента'),
                    'have' => array('module','log'),
                ),
                Object::idLicense      =>array( // 'oid' => 80,
                    'chars'=>array('license', 'lc', 'lock2', ':license'),
                    'label'=>array('Лицензии', 'Лицензия', 'Лицензии', 'лицензии'),
                    'have' => array('module','log'),
                ),
                Object::idSbReceiver =>array( 'id'=>'sbReceiver', // 'oid' => 81,
                    'chars'=>array('receiver', self::prefix, 'phonebook2', ':receiver'),
                    'label'=>array('Подписчики', 'Подписчик', 'Подписчики', 'подписчика'),
                    'have' => array('module','log'),
                ),
/*KPDMFU-FINAL-MIGRATE-OBJECT*/
//Object::idClients     =>array(73, 'clients'      ,'cl' , 0, 0, 0, 1, 0, 0, 0, 0, 0, 79, 0, 0, 'visitor'         , 'Клиенты'                , ':clients'       ,'Клиенты'               ,'Клиенты'               , 'Клиенты'               ),
//Object::idOrders      =>array(74, 'orders'       ,'or' , 0, 0, 0, 1, 0, 0, 0, 0, 0, 78, 0, 0, 'shoppingcart'          , 'Заказы'                 , ':orders'        ,'заказов'               ,'Заказы'                , 'Заказы'                ),
                ),
            ),
        ),
    );
    
}
