#!/opt/lampp/bin/php
<?php
/**
 * Yii command line script for Unix/Linux.
 *
 * This is the bootstrap script for running yiic on Unix/Linux.
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @link http://www.yiiframework.com/
 * @copyright Copyright &copy; 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
$dir  = dirname(__FILE__);
$root = dirname($dir);
defined('KPDMFU_CONSOLE') or define('KPDMFU_CONSOLE', true);
define('YII_CFG', DIRECTORY_SEPARATOR.'protected'.DIRECTORY_SEPARATOR.'config'.DIRECTORY_SEPARATOR.'console.php');
$config=$root.YII_CFG;
if (!file_exists($config))
    die("Config file is not found.");

require_once($dir.'/yiic.php');
